name: Keep Render Bot Alive

on:
  schedule:
    - cron: "*/1 * * * *"  # Cada 1 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up bot
        run: curl --silent https://chandelier-alert-bot.onrender.com || echo "Ping fallido"
